language: elixir
elixir: '1.8.0'
otp_release: '21.1'

sudo: required

services:
  - docker

before_install:
  - docker run --name guard-test-postgres -e POSTGRES_PASSWORD=doorman -e POSTGRES_USER=doorman_test -p 5433:5432 -d postgres
